### ISSUE TITLE
后端业务写完了，我怎么写前端小程序接口？

### ISSUE THREAD

**Issue by ArtfulCoderr** [quarkcms/quark-go#10]
希望作者不要生气的回复

**Comment by tangtanglove** [comment]
如果你用的是GIN框架的话，参考GIN文档开发就行了；如果直接用集成框架的话，可以参考[QuarkSmart](https://github.com/quarkcms/quark-smart/tree/main)；golang的框架使用方法大同小异，QuarkGo内部集成的是Echo框架
