### ISSUE TITLE
看一下这个bug （项目地址： http://43.139.150.116:6700/admin）

### ISSUE THREAD

**Issue by ArtfulCoderr** [quarkcms/quark-go#11]
func (resource *PayConfig) Actions(ctx *builder.Context) []interface{} {

	return []interface{}{
		(&actions.CreateModal{}).Init(resource.Title),
		(&actions.Delete{}).Init("批量删除"),
		(&actions.EditModal{}).Init("编辑"),
		(&actions.Delete{}).Init("删除"),
		(&actions.FormSubmit{}).Init(),
		(&actions.FormReset{}).Init(),
		(&actions.FormBack{}).Init(),
		(&actions.FormExtraBack{}).Init(),
	}
}

1.点击创建 直接·报错 路径（小程序配置这个菜单下的所有业务）
2.ordinary 这个角色访问不了控制台 403

**Comment by tangtanglove** [comment]
第一个问题：请拉取最新版本，有一处笔误造成的；
第二个问题：你没有给予控制台权限造成的，已帮你处理。
