### ISSUE TITLE
项目无法启动

### ISSUE THREAD

**Issue by qdsay** [quarkcms/quark-go#13]
启动提示：vendor/modernc.org/sqlite/lib/sqlite_darwin_amd64.go:158407:9: undefined: libc.Xpread

**Comment by tangtanglove** [comment]
因为Sqlite驱动使用了CGO，所以报错了，可以参考下面的解决方法：
https://www.cnblogs.com/xuejiale/p/10567217.html

**Comment by tangtanglove** [comment]
使用：github.com/mattn/go-sqlite3包也能解决；
Gorm相关文档：https://gorm.io/zh_CN/docs/connecting_to_the_database.html#SQLite

**Comment by qdsay** [comment]
modernc.org/sqlite 由 casbin 的 gorm-adapter 引入，修改这个第三方包么？
