### ISSUE TITLE
使用：github.com/mattn/go-sqlite3包也能解决；

### ISSUE THREAD

**Issue by qdsay** [quarkcms/quark-go#14]
modernc.org/sqlite 由 casbin 的 gorm-adapter 引入，修改这个第三方包么？

**Comment by qdsay** [comment]
升级Go到go1.20.6，解决...

**Comment by tangtanglove** [comment]
如果开发中型项目，可以用[QuarkSmart](https://github.com/quarkcms/quark-smart)
