### ISSUE TITLE
how to redirect to login page when occur 401 resonse code

### ISSUE THREAD

**Issue by windzhu0514** [quarkcms/quark-go#20]
Response status:401

**Comment by quarkcloudio** [comment]
发一下截图

**Comment by windzhu0514** [comment]
> 发一下截图

![image](https://github.com/quarkcloudio/quark-go/assets/5474294/2df19f77-80e6-437e-8710-357b73c242fb)

**Comment by quarkcloudio** [comment]
截图全一点儿

**Comment by quarkcloudio** [comment]
是登录之后报的错误吗？

**Comment by windzhu0514** [comment]
![image](https://github.com/quarkcloudio/quark-go/assets/5474294/e9b4cd5b-2899-4430-a1c2-6f0e7314d63e)
会话过期后，重新请求页面的时候

**Comment by quarkcloudio** [comment]
最新版已修正
