### ISSUE TITLE
按照教程无法对菜单绑定权限，新建角色登录后页面空白

### ISSUE THREAD

**Issue by windzhu0514** [quarkcms/quark-go#23]
新建菜单没有绑定权限操作
![image](https://github.com/quarkcloudio/quark-go/assets/5474294/384ed337-2e4a-49c1-8d4a-26bb3b6ebcc4)

![image](https://github.com/quarkcloudio/quark-go/assets/5474294/0dcad087-9fbe-4718-97ae-ed209fd26fc7)

**Comment by tangtanglove** [comment]
菜单类型选按钮
