### ISSUE TITLE
Select组件在列表页可编辑状态下不显示Label值

### ISSUE THREAD

**Issue by windzhu0514** [quarkcms/quark-go#26]
![image](https://github.com/quarkcloudio/quark-go/assets/5474294/4a55496b-6e7a-4cc7-8ca2-bbb600dcc05c)

**Comment by quarkcloudio** [comment]
问题已修复，可使用最新版或者直接更新UI文件

**Comment by windzhu0514** [comment]
> 问题已修复，可使用最新版或者直接更新UI文件

好的
