### ISSUE TITLE
List组件的数据无法展示

### ISSUE THREAD

**Issue by windzhu0514** [quarkcms/quark-go#28]
按照官方文档的例子定义List组件，数据库对应表格字段名是`list`
```go
field.
	List("list", "嵌套表单组件").
	SetButton("添加数据","bottom").
	SetItem(func () interface{} {

		return field.Group([]interface{}{
			field.Text("title", "标题"),
			field.Number("num","奖品数量"),
			field.Number("probability","中奖概率"),
		})
	})
```
页面上填入数据保存后，据库表list字段的值为：`[{"num":100,"probability":20,"title":"主题"}]`

页面展示时报错
![image](https://github.com/quarkcloudio/quark-go/assets/5474294/fefd4c52-bd28-4824-8c58-6f108a87934d)

**Comment by tangtanglove** [comment]
list组件的数据，在回调函数里自行解析一下吧；列表不能解析json数据
