### ISSUE TITLE
升级后所有的编辑失败

### ISSUE THREAD

**Issue by qdsay** [quarkcms/quark-go#31]
call of reflect.Value.NumField on map Value goroutine 50 [running]:\nmain.RootRunner.Recover.RecoverWithConfig.func1.1.1()\n\t/Users/star/Workspace/go/media/backend/vendor/github.com/labstack/echo/v4/middleware/recover.go:93 +0x15d\npanic({0x10b8610c0?, 0xc00090aa08?})\n\t/usr/local/go/src/runtime/panic.go:770 +0x132\nreflect.flag.mustBe(...)\n\t/usr/local/go/src/reflect/value.go:233\nreflect.Value.NumField

**Comment by tangtanglove** [comment]
贴一下代码

**Comment by tangtanglove** [comment]
拉取最新的版本，再试一下
