### ISSUE TITLE
如何通过nginx路由转发的quark-go开发的服务

### ISSUE THREAD

**Issue by windzhu0514** [quarkcms/quark-go#32]
比如域名为`example.com/biz`，如何支持这种path前缀

**Comment by windzhu0514** [comment]
我觉的可以在 `builder.Config` 里加个配置 `URLPathPrefix`，在所有URL的地方都加上自定义的 PATH 前缀

**Comment by tangtanglove** [comment]
使用Nginx返代不可以吗？

**Comment by windzhu0514** [comment]
一些url是代码里写死的，反代了会无法访问；你用ngix反代尝试过了吗？是否是我使用方式不对

**Comment by tangtanglove** [comment]
nginx rewrite试试

**Comment by windzhu0514** [comment]
nginx配置
```
server {
        listen 9999;
        location /alert/ {
                rewrite ^/alert(.*)$ $1 break;
                proxy_pass http://localhost:8080/;
        }
}
```

服务监听端口：`:8080`
请求地址：`http://10.181.34.34:9999/alert/admin/#`

提示一下错误
![image](https://github.com/quarkcloudio/quark-go/assets/5474294/d9d9f6e6-d2e4-4d5d-80a7-0f8593102054)

@tangtanglove

**Comment by tangtanglove** [comment]
前端接口规则是定死的，虽然可以使用重新定义路由路径来实现，但不鼓励这样改

**Comment by windzhu0514** [comment]
> 前端接口规则是定死的，虽然可以使用重新定义路由路径来实现，但不鼓励这样改

是否可以考虑支持一下统一的path后缀，支持自定义path后缀可以在企业里通过域名+path后缀使用。
比如：https://example.com/manager，内部所有地址都会自动加上/manager path
