### ISSUE TITLE
权限分配问题

### ISSUE THREAD

**Issue by ArtfulCoderr** [quarkcms/quark-go#33]
没有菜单绑定权限选项
![image](https://github.com/user-attachments/assets/e999b5b1-f8bd-4dbc-bfd9-9ecd9e90caaf)
已经同步权限了
![image](https://github.com/user-attachments/assets/ae81b87f-1586-40c5-a249-6b453bc37fa6)
角色已经创建好了
![image](https://github.com/user-attachments/assets/d1a28805-a92d-4a54-a1a3-9ec270485eb7)
![image](https://github.com/user-attachments/assets/383bce98-06fd-4d0c-9c14-547033c5919b)
账号也已经创建好了
![image](https://github.com/user-attachments/assets/d3613bfb-4ed0-4b6b-b05f-ed6c23fe6ef6)
但是访问就是403
作者时间帮个忙，我这边不知道那一步做错了

**Comment by fivepmcoder** [comment]
绑定权限在按钮选项中，可以在菜单下级中创建一个按钮选择要绑定的权限，之后再角色里面选择上就好了

![image](https://github.com/user-attachments/assets/9d15ae0c-9065-402e-a6a0-2713027250f0)

![image](https://github.com/user-attachments/assets/e10df3eb-c6ff-4d5e-aece-88c1eea84d7c)

**Comment by ArtfulCoderr** [comment]
谢谢，解决了，现在问登录直接去控制台，我希望有些用户不给他看控制台，然后就是怎么自定义控制台

**Comment by fivepmcoder** [comment]
[quark-go/pkg/app/admin/service/logins/index.go](https://github.com/quarkcloudio/quark-go/tree/v2/pkg/app/admin/service/logins/index.go) 
这个文件里找到下面的方法，里面配置登陆后跳转地址
``` go
// 初始化
func (p *Index) Init(ctx *builder.Context) interface{} {

	// 登录页面Logo
	p.Logo = false

	// 登录页面标题
	p.Title = "QuarkGo"

	// 登录页面子标题
	p.SubTitle = "信息丰富的世界里，唯一稀缺的就是人类的注意力"

	// 登录后跳转地址
	p.Redirect = "/layout/index?api=/api/admin/dashboard/index/index"

	return p
}
```

**Comment by ArtfulCoderr** [comment]
谢谢兄弟，这个是也是可以的，但是可以的话作者有时间提供登录以后跳转的hook，可以避免必修要去控制台页面这种，再次感谢你
