### ISSUE TITLE
不显示自定义组件，有没有办法自己扩展组件

### ISSUE THREAD

**Issue by ArtfulCoderr** [quarkcms/quark-go#36]
这个是我自己按照Antd和框架本身封转编写的组件代码：
package colorpicker

import (
	"github.com/quarkcloudio/quark-go/v2/pkg/app/admin/component/component"
	"github.com/quarkcloudio/quark-go/v2/pkg/app/admin/component/table"
	"github.com/quarkcloudio/quark-go/v2/pkg/utils/hex"
	"github.com/quarkcloudio/quark-smart/internal/admin/components"
)

type Component struct {
	ComponentKey   string                 `json:"componentkey"`          // 组件标识
	Component      string                 `json:"component"`             // 组件名称
	Label          string                 `json:"label,omitempty"`       // label 标签的文本
	Name           string                 `json:"name,omitempty"`        // 字段名，支持数组
	LabelAlign     string                 `json:"labelAlign,omitempty"`  // 标签文本对齐方式
	LabelCol       interface{}            `json:"labelCol,omitempty"`    // label 标签布局，同 <Col> 组件，设置 span offset 值，如 {span: 3, offset: 12} 或 sm: {span: 3, offset: 12}。你可以通过 Form 的 labelCol 进行统一设置，不会作用于嵌套 Item。当和 Form 同时设置时，以 Item 为准
	ShowOnIndex    bool                   `json:"-"`                     // 在列表页展示
	ShowOnDetail   bool                   `json:"-"`                     // 在详情页展示
	ShowOnCreation bool                   `json:"-"`                     // 在创建页面展示
	ShowOnUpdate   bool                   `json:"-"`                     // 在编辑页面展示
	ShowOnExport   bool                   `json:"-"`                     // 在导出的Excel上展示
	ShowOnImport   bool                   `json:"-"`                     // 在导入Excel上展示
	Column         *table.Column          `json:"-"`                     // 列表页、详情页中列属性
	Callback       interface{}            `json:"-"`                     // 回调函数
	Style          map[string]interface{} `json:"style,omitempty"`       // 自定义样式
	Placeholder    string                 `json:"placeholder,omitempty"` // 占位符
	AllowClear     bool                   `json:"allowClear"`
	ShowText       bool                   `json:"showText"`
	DefaultValue   string                 `json:"defaultValue,omitempty"`
	Size           string                 `json:"size"`
}

// 初始化组件
func New() *Component {
	return (&Component{}).Init()
}

// 初始化
func (p *Component) Init() *Component {
	p.Component = "colorPicker"
	p.LabelAlign = "right"

	p.ShowOnIndex = true
	p.ShowOnDetail = true
	p.ShowOnCreation = true
	p.ShowOnUpdate = true
	p.ShowOnExport = true
	p.ShowOnImport = true
	p.AllowClear = true
	p.Column = (&table.Column{}).Init()
	p.SetWidth(200)
	p.SetKey(component.DEFAULT_KEY, component.DEFAULT_CRYPT)

	return p
}

func (p *Component) ColorPicker(params ...interface{}) *Component {
	return components.FieldParser(New(), params, "请输入").(*Component)
}

// Field 的长度，我们归纳了常用的 Field 长度以及适合的场景，支持了一些枚举 "xs" , "s" , "m" , "l" , "x"
func (p *Component) SetWidth(width interface{}) *Component {
	style := make(map[string]interface{})

	for k, v := range p.Style {
		style[k] = v
	}

	style["width"] = width
	p.Style = style

	return p
}

// 设置Key
func (p *Component) SetKey(key string, crypt bool) *Component {
	p.ComponentKey = hex.Make(key, crypt)

	return p
}

package components

import "reflect"

// 解析字段
func FieldParser(field interface{}, params []interface{}, placeholder string) interface{} {
	v := reflect.ValueOf(field).Elem()

	switch len(params) {
	case 1:
		v.FieldByName("Name").Set(reflect.ValueOf(params[0].(string)))
	case 2:
		v.FieldByName("Name").Set(reflect.ValueOf(params[0]))
		v.FieldByName("Label").Set(reflect.ValueOf(params[1]))
	case 3:
		v.FieldByName("Name").Set(reflect.ValueOf(params[0]))
		v.FieldByName("Label").Set(reflect.ValueOf(params[1]))

		// 判断是否为闭包函数
		closure, ok := params[2].(func() interface{})
		if ok {
			v.FieldByName("Callback").Set(reflect.ValueOf(closure))
		}
	}

	if placeholder != "" && len(params) > 1 {
		v.FieldByName("Placeholder").Set(reflect.ValueOf(placeholder + params[1].(string)))
	}

	return field
}
用法：
field.Select("status", "状态").
			SetOptions([]*selectfield.Option{
				{Value: 1, Label: "正常"},
				{Value: 0, Label: "禁用"},
			}).
			SetFilters(true).
			SetDefault(1),

		colorPickerCmp.ColorPicker("color_right", "color_right"), 
问题页面正常显示 状态字段 但是不显示 自定义组件

**Comment by tangtanglove** [comment]
代码贴的有点儿乱，重新贴一下代码
