### ISSUE TITLE
入门 文档 有问题

### ISSUE THREAD

**Issue by kuchaguangjie** [quarkcms/quark-go#38]
1. `"github.com/glebarez/sqlite""` 这里 多了个 "
2. 按照文档 写好代码后 启动报错: 
     > go/pkg/mod/gorm.io/plugin/dbresolver@v1.4.1/dbresolver.go:147:5: unknown field PreparedSQL in struct literal of type gorm.PreparedStmtDB

**Comment by tangtanglove** [comment]
update dbresolve v1.5.3

**Comment by tangtanglove** [comment]
文档问题已修复
