### ISSUE TITLE
能不能插入原生html或者自己实现antd组件（有些antd组件还没有实现能不能自己实现）

### ISSUE THREAD

**Issue by ArtfulCoderr** [quarkcms/quark-go#40]
能不能插入原生html或者自己实现antd组件（有些antd组件还没有实现能不能自己实现）

**Comment by tangtanglove** [comment]
自己编译前端引擎即可：https://github.com/quarkcloudio/quark-ui

**Comment by ArtfulCoderr** [comment]
那就我想新增组件的直接参与quark-ui项目就可以吗？或者自己本地编译替换web目录

**Comment by tangtanglove** [comment]
可以的，你想增加什么组件，如果是通用的也可以提交pr
