### ISSUE TITLE
行为action，如何设置隐藏

### ISSUE THREAD

**Issue by soul-key** [quarkcms/quark-go#43]
需求：功能列表，操作列有些按钮需要在特定条件下隐藏（比如退款，已退款的就不能在显示这个按钮）

**Comment by tangtanglove** [comment]
action.Name = "<%= (id==1 ? '' : '删除') %>"

**Comment by tangtanglove** [comment]
参考这里：https://github.com/quarkcloudio/quark-go/blob/v3/app/admin/actions/delete_special.go#L18
