### ISSUE TITLE
3.5.3 启动报错

### ISSUE THREAD

**Issue by fantasticbin** [quarkcms/quark-go#44]
报错信息如下：

github.com/quarkcloudio/quark-go/v3/template/admin/component/table

../../go/pkg/mod/github.com/quarkcloudio/quark-go/v3@v3.5.3/template/admin/component/table/tree_bar.go:285:4: cannot use stringy.New(keyName).CamelCase("?", "") (value of type stringy.StringManipulation) as string value in argument to item.FieldByName
../../go/pkg/mod/github.com/quarkcloudio/quark-go/v3@v3.5.3/template/admin/component/table/tree_bar.go:291:4: cannot use stringy.New(parentKeyName).CamelCase("?", "") (value of type stringy.StringManipulation) as string value in argument to item.FieldByName
../../go/pkg/mod/github.com/quarkcloudio/quark-go/v3@v3.5.3/template/admin/component/table/tree_bar.go:296:4: cannot use stringy.New(titleName).CamelCase("?", "") (value of type stringy.StringManipulation) as string value in argument to item.FieldByName

**Comment by fantasticbin** [comment]
初步查明 github.com/gobeam/stringy 从0.0.6升到0.0.7之后 stringy.New().CamelCase() 的返回值已改成 StringManipulation 而导致

pr已提交 #45

**Comment by tangtanglove** [comment]
依赖升级涉及到改动的地方还是比较多的，我需要评估一下

**Comment by tangtanglove** [comment]
已处理
