### ISSUE TITLE
关于组件SetCallback的建议

### ISSUE THREAD

**Issue by fantasticbin** [quarkcms/quark-go#46]
是否可在组件.SetCallback()时，将组件结构体本身传入进来灵活控制？

目前有一个需求：列表项之中满足某一条件时特殊展示

**Comment by tangtanglove** [comment]
是支持的

**Comment by tangtanglove** [comment]
![image](https://github.com/user-attachments/assets/e8fbef55-29c3-45f9-b70d-faab04c55d14)

**Comment by tangtanglove** [comment]
参考这里：https://github.com/quarkcloudio/quark-go/blob/v3/app/admin/resources/user.go#L91C1-L91C1

**Comment by fantasticbin** [comment]
这里无法判断列表项之中满足某一条件的情况吧？我这里设想的是通过方法来确定某些记录后，使用SetStyle或者SetClass来达到特殊展示的目的

**Comment by tangtanglove** [comment]
可以判断的

**Comment by tangtanglove** [comment]
使用这种方式：p.Field["username"].(string)，可以获取当列的字段值，返回的值支持html标签

**Comment by fantasticbin** [comment]
{
    "time": "2024-11-20T11:41:39.270036+08:00",
    "level": "-",
    "prefix": "echo",
    "file": "recover.go",
    "line": "119",
    "message": "[PANIC RECOVER] interface conversion: interface {} is time.Time, not string goroutine 11 [running]:\nmain.main.Recover.RecoverWithConfig.func1.1.1()\n\t/Users/fantasticbin/GolandProjects/bin-admin/vendor/github.com/labstack/echo/v4/middleware/recover.go:99 +0x134\npanic({0x105c85d00?, 0x1400040cff0?})\n\t/opt/homebrew/opt/go/libexec/src/runtime/panic.go:785 +0x124\ngithub.com/quarkcloudio/quark-smart/v2/internal/app/admin/resource.(*Vip).Fields.func1()\n\t/Users/fantasticbin/GolandProjects/bin-admin/internal/app/admin/resource/vip.go:67 +0xcc\ngithub.com/quarkcloudio/quark-go/v3/template/admin/resource/requests.(*IndexRequest).performsList(0x1400040c360?, 0x140008ea0c0, {0x140006fa200, 0xa, 0x0?})\n\t/Users/fantasticbin/GolandProjects/bin-admin/vendor/github.com/quarkcloudio/quark-go/v3/template/admin/resource/requests/index.go:144 +0x33c\ngithub.com/quarkcloudio/quark-go/v3/template/admin/resource/requests.(*IndexRequest).QueryData(0x14000052fd7, 0x140008ea0c0)\n\t/Users/fantasticbin/GolandProjects/bin-admin/vendor/github.com/quarkcloudio/quark-go/v3/template/admin/resource/requests/index.go:74 +0x4c8\ngithub.com/quarkcloudio/quark-go/v3/template/admin/resource.(*Template).IndexRender(0x2?, 0x140008ea0c0)\n\t/Users/fantasticbin/GolandProjects/bin-admin/vendor/github.com/quarkcloudio/quark-go/v3/template/admin/resource/resource.go:287 +0x84\nreflect.Value.call({0x105e06ae0?, 0x10697e740?, 0x10697e740?}, {0x1058b6b82, 0x4}, {0x14000053760, 0x1, 0x0?})\n\t/opt/homebrew/opt/go/libexec/src/reflect/value.go:581 +0x97c\nreflect.Value.Call({0x105e06ae0?, 0x10697e740?, 0x105aa3740?}, {0x14000053760?, 0x0?, 0x1057ecf40?})\n\t/opt/homebrew/opt/go/libexec/src/reflect/value.go:365 +0x94\ngithub.com/quarkcloudio/quark-go/v3.(*Engine).handleParser(0x1058c58f1?, 0x140008ea0c0)\n\t/Users/fantasticbin/GolandProjects/bin-admin/vendor/github.com/quarkcloudio/quark-go/v3/engine.go:377 +0x2c8\ngithub.com/quarkcloudio/quark-go/v3.(*Engine).routeMappingParser.func1(0x140008ea0c0?)\n\t/Users/fantasticbin/GolandProjects/bin-admin/vendor/github.com/quarkcloudio/quark-go/v3/engine.go:421 +0x28\ngithub.com/quarkcloudio/quark-go/v3.(*Engine).echoHandle(0x1400019e000, {0x1058d862b, 0x1a}, 0x1400081b350, {0x105e48ef0, 0x140008ca000})\n\t/Users/fantasticbin/GolandProjects/bin-admin/vendor/github.com/quarkcloudio/quark-go/v3/engine.go:476 +0x2cc\ngithub.com/quarkcloudio/quark-go/v3.(*Engine).GET.func1({0x105e48ef0?, 0x140008ca000?})\n\t/Users/fantasticbin/GolandProjects/bin-admin/vendor/github.com/quarkcloudio/quark-go/v3/engine.go:491 +0x44\ngithub.com/labstack/echo/v4.(*Echo).add.func1({0x105e48ef0, 0x140008ca000})\n\t/Users/fantasticbin/GolandProjects/bin-admin/vendor/github.com/labstack/echo/v4/echo.go:587 +0x50\nmain.main.Recover.RecoverWithConfig.func1.1({0x105e48ef0, 0x140008ca000})\n\t/Users/fantasticbin/GolandProjects/bin-admin/vendor/github.com/labstack/echo/v4/middleware/recover.go:130 +0xe8\ngithub.com/labstack/echo/v4/middleware.LoggerWithConfig.func2.1({0x105e48ef0, 0x140008ca000})\n\t/Users/fantasticbin/GolandProjects/bin-admin/vendor/github.com/labstack/echo/v4/middleware/logger.go:125 +0xa0\ngithub.com/labstack/echo/v4.(*Echo).ServeHTTP(0x140007a1d48, {0x105e32ac0, 0x140007a20e0}, 0x14000794000)\n\t/Users/fantasticbin/GolandProjects/bin-admin/vendor/github.com/labstack/echo/v4/echo.go:674 +0x304\nnet/http.serverHandler.ServeHTTP({0x1400040c030?}, {0x105e32ac0?, 0x140007a20e0?}, 0x6?)\n\t/opt/homebrew/opt/go/libexec/src/net/http/server.go:3210 +0xbc\nnet/http.(*conn).serve(0x140008b0000, {0x105e351e8, 0x1400017fbc0})\n\t/opt/homebrew/opt/go/libexec/src/net/http/server.go:2092 +0x4fc\ncreated by net/http.(*Server).Serve in goroutine 1\n\t/opt/homebrew/opt/go/libexec/src/net/http/server.go:3360 +0x3dc\n\ngoroutine 1 [IO wait]:\ninternal/poll.runtime_pollWait(0x12db85780, 0x72)\n\t/opt/homebrew/opt/go/libexec/src/runtime/netpoll.go:351 +0xa0\ninternal/poll.(*pollDesc).wait(0x140003f6580?, 0x104bdca88?, 0x0)\n\t/opt/homebrew/opt/go/libexec/src/internal/poll/fd_poll_runtime.go:84 +0x28\ninternal/poll.(*pollDesc).waitRead(...)\n\t/opt/homebrew/opt/go/libexec/src/internal/poll/fd_poll_runtime.go:89\ninternal/poll.(*FD).Accept(0x140003f6580)\n\t/opt/homebrew/opt/go/libexec/src/internal/pol\n"
}

**Comment by fantasticbin** [comment]
![Snipaste_2024-11-20_11-44-24](https://github.com/user-attachments/assets/2d3b72df-b706-41a1-9fd2-bc1900721319)

**Comment by tangtanglove** [comment]
![image](https://github.com/user-attachments/assets/ed82695d-91bb-49ef-8d2c-179a21f09509)
断言类型错了，不是string类型的

**Comment by fantasticbin** [comment]
![Snipaste_2024-11-20_11-57-19](https://github.com/user-attachments/assets/6368555e-0f3a-4a45-ab04-9e396f78642f)

html被直接原样输出了

**Comment by fantasticbin** [comment]
text组件会直接渲染，datetime不会

**Comment by fantasticbin** [comment]
![Snipaste_2024-11-20_12-37-56](https://github.com/user-attachments/assets/528f9d2e-82c8-446a-a5e5-22671a56cf8c)

另外text组件使用html渲染后，直接编辑会将html代码填充进去，然后重复点击会持续嵌套html，并将html代码一并入库

**Comment by tangtanglove** [comment]
1、datetime原样输出，你暂时可以使用OnlyOnIndex()等方法去控制显示机制
2、text组件使用html渲染后，直接编辑会将html代码填充进去，这个问题没法处理，把可编辑列给去掉吧

**Comment by fantasticbin** [comment]
第2点可考虑在SetEditable方法中再增加一个参数用来控制是否编辑原输出，还是需过滤html标签，模板中过滤html标签不难

**Comment by tangtanglove** [comment]
好的，我评估一下，欢迎pr

**Comment by fantasticbin** [comment]
😅看了一下前端不好改，还是先写别的，你评估好了能改直接改
最好再增加一个方法去设置，不要改原方法了，不然就无法兼容老版本的代码

**Comment by tangtanglove** [comment]
先关了，有时间再处理
