### ISSUE TITLE
文档并不详尽

### ISSUE THREAD

**Issue by Soul-Yang** [quarkcms/quark-go#47]
①  弹出层与抽屉，只能用来创建吗（按钮位置如何设置才能放到列表的每行操作里，比如用来编辑）？
②  弹出层如何展示其他表的信息，比如（用户列表页，操作里面有个  【用户钱包】 按钮，点击后打开的是对应钱包表的数据）
③ 弹出层只能跟数据表绑定吗？ 太死板了，如何做一些 自由发挥的页面展示逻辑，是否可以考虑支持，毕竟 后台不只有对数据表增删改查

**Comment by tangtanglove** [comment]
① 弹出层与抽屉可以用来编辑
② 弹出层是可以展示其他信息的
③ 弹出层可以定义任何操作，不一定绑定数据

**Comment by tangtanglove** [comment]
可以看这里的示例：https://github.com/quarkcloudio/quark-go/blob/v3/app/admin/actions/modal_form.go

**Comment by tangtanglove** [comment]
如果有问题，可以把代码贴上来，文档后续会完善

**Comment by Soul-Yang** [comment]
非常感谢给答疑解惑，已正确完成功能。期待后续的完善文档能早早和大家见面
