### ISSUE TITLE
按照文档gin框架运行直接报错

### ISSUE THREAD

**Issue by ArtfulCoderr** [quarkcms/quark-go#5]
Downloading static files, please wait...
Download static files failed! 
 Please goto https://github.com/quarkcms/quark-go/tree/main/website url to download it
 After downloading, you must make 'install.lock' file in the website dir
panic: Get "https://github.com/quarkcms/quark-go/tree/main/website/": dial tcp 199.59.149.235:443: connectex: A connection attempt failed because the connected p
arty did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

goroutine 1 [running]:
        C:/Users/project/go/pkg/mod/github.com/quarkcms/quark-go@v1.2.8/pkg/github/github.go:54 +0x93
github.com/quarkcms/quark-go/pkg/github.handle({{0x0, 0x0}, 0x0, {0x0, 0x0}, 0x0}, {0xe9695b, 0x37}, {0xe9698a, 0x7}, ...)
        C:/Users/project/go/pkg/mod/github.com/quarkcms/quark-go@v1.2.8/pkg/github/github.go:67 +0x10c
github.com/quarkcms/quark-go/pkg/github.Download({0xe9695b, 0x37}, {0x0?, 0x1?})
        C:/Users/project/go/pkg/mod/github.com/quarkcms/quark-go@v1.2.8/pkg/github/github.go:39 +0x185
github.com/quarkcms/quark-go/pkg/builder.New(0xc0006880f0)
        C:/Users/project/go/pkg/mod/github.com/quarkcms/quark-go@v1.2.8/pkg/builder/engine.go:109 +0x1a7
main.main()
github.com/quarkcms/quark-go/pkg/github.failedPrint({0xd2d440, 0xc000272ab0})
        C:/Users/project/go/pkg/mod/github.com/quarkcms/quark-go@v1.2.8/pkg/github/github.go:54 +0x93
github.com/quarkcms/quark-go/pkg/github.handle({{0x0, 0x0}, 0x0, {0x0, 0x0}, 0x0}, {0xc0695b, 0x37}, {0xc0698a, 0x7}, ...)
        C:/Users/project/go/pkg/mod/github.com/quarkcms/quark-go@v1.2.8/pkg/github/github.go:67 +0x10c
github.com/quarkcms/quark-go/pkg/github.Download({0xc0695b, 0x37}, {0x0?, 0x1?})
        C:/Users/project/go/pkg/mod/github.com/quarkcms/quark-go@v1.2.8/pkg/github/github.go:39 +0x185
github.com/quarkcms/quark-go/pkg/builder.New(0xc00058e190)
        C:/Users/project/go/pkg/mod/github.com/quarkcms/quark-go@v1.2.8/pkg/builder/engine.go:109 +0x1a7
main.main()
        C:/Users/project/Desktop/demo/main.go:33 +0x273
exit status 2

**Comment by tangtanglove** [comment]
因为github被墙，只能手动下载[website](https://github.com/quarkcms/quark-go/tree/1.2/website)静态文件。
