### ISSUE TITLE
用gin框架启动出现这种bug？

### ISSUE THREAD

**Issue by ArtfulCoderr** [quarkcms/quark-go#6]
goroutine 1 [running]:
github.com/quarkcms/quark-go/pkg/builder.(*Engine).Use(0xc0002de620, {0x1559d20?, 0x1704bd8?})
        C:/Users/project/go/pkg/mod/github.com/quarkcms/quark-go@v1.2.8/pkg/builder/engine.go:310 +0x1f9
main.main()
        C:/Users/project/Desktop/demo/main.go:34 +0x28b

Process finished with the exit code 2

**Comment by tangtanglove** [comment]
文档已修正，请查看最新文档

**Comment by ArtfulCoderr** [comment]
谢谢，麻烦你了
