### ISSUE TITLE
按照文档写post服务，field := &builder.AdminField{}报错

### ISSUE THREAD

**Issue by ArtfulCoderr** [quarkcms/quark-go#7]
// 字段
func (p *Post) Fields(ctx *builder.Context) []interface{} {

	field := &builder.AdminField{}

	return []interface{}{
		field.ID("id", "ID"),

		field.Text("title", "标题").
			SetRules(
				[]string{
					"required",
				},
				map[string]string{
					"required": "标题必须填写",
				},
			),

		field.Editor("content", "内容").OnlyOnForms(),

		field.Switch("status", "状态").
			SetTrueValue("正常").
			SetFalseValue("禁用").
			SetEditable(true).
			SetDefault(true),
	}
}

**Comment by tangtanglove** [comment]
文档已修正，请查看最新文档
