### ISSUE TITLE
创建新的角色以后授权菜单然后登录新角色的账号直接403，希望作者帮助，系统已经开发完了我就卡在这里了

### ISSUE THREAD

**Issue by ArtfulCoderr** [quarkcms/quark-go#8]

**Comment by tangtanglove** [comment]
你好，请看一下文档：https://www.quarkcms.com/quark-go/builtin.html#%E6%B7%BB%E5%8A%A0%E8%8F%9C%E5%8D%95

**Comment by tangtanglove** [comment]
是这样的：所有的菜单必须与权限对应起来，403说明这个URL权限没有分配给角色

**Comment by ArtfulCoderr** [comment]
GuradName 默认admin是可以的吧，我就菜单绑定权限以后没有生效

**Comment by tangtanglove** [comment]
是可以的

**Comment by tangtanglove** [comment]
可以用开发者工具看一是哪个URL，再检查一下URL是否绑定了菜单

**Comment by tangtanglove** [comment]
已帮你处理，权限要同步一下才行的

**Comment by ArtfulCoderr** [comment]
谢谢，麻烦你了

**Comment by tangtanglove** [comment]
写了一个小Demo，可以参考一下：https://github.com/quarkcms/wechat-helper

**Comment by xuchen-xiaoying** [comment]
用了最新版本 v2.1.18，依然有这个错误
- 权限已经同步

![image](https://github.com/quarkcms/quark-go/assets/94154028/677657f1-9bb3-4cef-8010-a843317c4123)

- 创建角色

![image](https://github.com/quarkcms/quark-go/assets/94154028/9c6c6e43-3f0e-492b-b6e8-763d70cbd056)

- 创建管理员
![image](https://github.com/quarkcms/quark-go/assets/94154028/2b14d150-ba6a-4487-8978-d4f7dccea44a)

- 新管理员登录
![image](https://github.com/quarkcms/quark-go/assets/94154028/79c8615c-96c5-472a-a667-996593f4a611)
